//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 11:44:27 AM CEST 
//


package com.wroom.rentingservice.soap.xsd;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bundle" type="{http://ftn.com/wroom-agent/xsd}BundledRequestsSoap"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bundle"
})
@XmlRootElement(name = "SendBundleResponse")
public class SendBundleResponse {

    @XmlElement(required = true)
    protected BundledRequestsSoap bundle;

    /**
     * Gets the value of the bundle property.
     * 
     * @return
     *     possible object is
     *     {@link BundledRequestsSoap }
     *     
     */
    public BundledRequestsSoap getBundle() {
        return bundle;
    }

    /**
     * Sets the value of the bundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link BundledRequestsSoap }
     *     
     */
    public void setBundle (BundledRequestsSoap value) {
        this.bundle = value;
    }

}
