//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.20 at 03:29:38 PM CEST 
//


package xwsagent.wroomagent.soap.xsd;

import java.util.Date;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AdSoap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AdSoap"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://ftn.com/wroom-agent/xsd}id"/&gt;
 *         &lt;element name="publishDate" type="{http://ftn.com/wroom-agent/xsd}date"/&gt;
 *         &lt;element name="availableFrom" type="{http://ftn.com/wroom-agent/xsd}date"/&gt;
 *         &lt;element name="availableTo" type="{http://ftn.com/wroom-agent/xsd}date"/&gt;
 *         &lt;element name="mileLimit" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="gps" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="address" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="vehicleId" type="{http://ftn.com/wroom-agent/xsd}id"/&gt;
 *         &lt;element name="priceListId" type="{http://ftn.com/wroom-agent/xsd}id"/&gt;
 *         &lt;element name="locationId" type="{http://ftn.com/wroom-agent/xsd}id"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AdSoap", propOrder = {
    "id",
    "publishDate",
    "availableFrom",
    "availableTo",
    "mileLimit",
    "gps",
    "deleted",
    "address",
    "vehicleId",
    "priceListId",
    "locationId"
})
public class AdSoap {

    protected long id;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date publishDate;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date availableFrom;
    
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date availableTo;
    
    protected double mileLimit;
    
    protected boolean gps;
    
    protected boolean deleted;
    
    @XmlElement(required = true)
    protected String address;
    
    protected long vehicleId;
    
    protected long priceListId;
    
    protected long locationId;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the publishDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * Sets the value of the publishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPublishDate(Date value) {
        this.publishDate = value;
    }

    /**
     * Gets the value of the availableFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getAvailableFrom() {
        return availableFrom;
    }

    /**
     * Sets the value of the availableFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailableFrom(Date value) {
        this.availableFrom = value;
    }

    /**
     * Gets the value of the availableTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public Date getAvailableTo() {
        return availableTo;
    }

    /**
     * Sets the value of the availableTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAvailableTo(Date value) {
        this.availableTo = value;
    }

    /**
     * Gets the value of the mileLimit property.
     * 
     */
    public double getMileLimit() {
        return mileLimit;
    }

    /**
     * Sets the value of the mileLimit property.
     * 
     */
    public void setMileLimit(double value) {
        this.mileLimit = value;
    }

    /**
     * Gets the value of the gps property.
     * 
     */
    public boolean isGps() {
        return gps;
    }

    /**
     * Sets the value of the gps property.
     * 
     */
    public void setGps(boolean value) {
        this.gps = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAddress(String value) {
        this.address = value;
    }

    /**
     * Gets the value of the vehicleId property.
     * 
     */
    public long getVehicleId() {
        return vehicleId;
    }

    /**
     * Sets the value of the vehicleId property.
     * 
     */
    public void setVehicleId(long value) {
        this.vehicleId = value;
    }

    /**
     * Gets the value of the priceListId property.
     * 
     */
    public long getPriceListId() {
        return priceListId;
    }

    /**
     * Sets the value of the priceListId property.
     * 
     */
    public void setPriceListId(long value) {
        this.priceListId = value;
    }

    /**
     * Gets the value of the locationId property.
     * 
     */
    public long getLocationId() {
        return locationId;
    }

    /**
     * Sets the value of the locationId property.
     * 
     */
    public void setLocationId(long value) {
        this.locationId = value;
    }

}
