
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.06.14 at 11:01:46 PM CEST 



package com.wroom.adsservice.soap.xsd;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface
 * generated in the com.wroom.adsservice.wsdl package.
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.wroom.adsservice.wsdl
     * 
     */
    public ObjectFactory() {
    }


    /**
     * Create an instance of {@link CommentRequest }
     * 
     */
    public CommentRequest createCommentRequest() {
        return new CommentRequest();
    }

    /**
     * Create an instance of {@link CommentSoap }
     * 
     */
    public CommentSoap createCommentSoap() {
        return new CommentSoap();
    }

    /**
     * Create an instance of {@link CommentResponse }
     * 
     */
    public CommentResponse createCommentResponse() {
        return new CommentResponse();
    }

    /**
     * Create an instance of {@link SendAdRequest }
     * 
     */
    public SendAdRequest createSendAdRequest() {
        return new SendAdRequest();
    }

    /**
     * Create an instance of {@link AdSoap }
     * 
     */
    public AdSoap createAdSoap() {
        return new AdSoap();
    }

    /**
     * Create an instance of {@link SendAdResponse }
     * 
     */
    public SendAdResponse createSendAdResponse() {
        return new SendAdResponse();
    }

    /**
     * Create an instance of {@link CommentListRequest }
     * 
     */
    public CommentListRequest createCommentListRequest() {
        return new CommentListRequest();
    }

    /**
     * Create an instance of {@link CommentListResponse }
     * 
     */
    public CommentListResponse createCommentListResponse() {
        return new CommentListResponse();
    }


}
